# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3f493a3c1c21383a013f8fb5449cff1a6f022bd79ba6bc6e7297dfae9d89a05a543ac34a15ca09fa01e98aeba7108d7fbcc14691422898e12d4e8a42d157ff4

test:
  secret_key_base: 2fc686e2b3ff074f95ed7271285cb87f6a294c703ccd5572ce83ab7a8772c9e035329c2221fe90c459b960fc54e33ee16a3489909f09c085153f20ffa30adbfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
